from __future__ import annotations

"""Score-matrix preprocessing for binary Hough line detection."""

from .config import (
    ADAPTIVE_BUDGET_MASK_COMPONENT_REGION,
    ADAPTIVE_BUDGET_MASK_FINAL_HOUGH_INPUT,
    ADAPTIVE_BUDGET_MASK_REGION_OF_INTEREST,
    ADAPTIVE_BUDGET_MASK_SCORE_FLOOR,
    ADAPTIVE_BUDGET_MASK_STRONG_MATCH,
    CONNECTED_COMPONENT_BACKEND_CYTHON,
    CONNECTED_COMPONENT_BACKEND_PYTHON,
    CONNECTED_COMPONENT_BACKEND_SCIPY,
    FINAL_HOUGH_INPUT_MODE_REGION_OF_INTEREST,
    FINAL_HOUGH_INPUT_MODE_REGION_OF_INTEREST_AND_SCORE_FLOOR,
    FINAL_HOUGH_INPUT_MODE_REGION_OF_INTEREST_OR_SCORE_FLOOR,
    HoughPreprocessingConfig,
    MEDIAN_ABSOLUTE_DEVIATION_BACKEND_MANUAL_NUMPY,
    MEDIAN_ABSOLUTE_DEVIATION_BACKEND_SCIPY,
    SCORE_FLOOR_METHOD_MEAN_PLUS_STANDARD_DEVIATION,
    SCORE_FLOOR_METHOD_MEDIAN_PLUS_SCALED_MEDIAN_ABSOLUTE_DEVIATION,
    SUPPORTED_ADAPTIVE_BUDGET_MASKS,
    SUPPORTED_FINAL_HOUGH_INPUT_MODES,
    SUPPORTED_SCORE_FLOOR_METHODS,
)
from .region_of_interest import build_region_of_interest_hough_context

__all__ = [
    "ADAPTIVE_BUDGET_MASK_COMPONENT_REGION",
    "ADAPTIVE_BUDGET_MASK_FINAL_HOUGH_INPUT",
    "ADAPTIVE_BUDGET_MASK_REGION_OF_INTEREST",
    "ADAPTIVE_BUDGET_MASK_SCORE_FLOOR",
    "ADAPTIVE_BUDGET_MASK_STRONG_MATCH",
    "CONNECTED_COMPONENT_BACKEND_CYTHON",
    "CONNECTED_COMPONENT_BACKEND_PYTHON",
    "CONNECTED_COMPONENT_BACKEND_SCIPY",
    "FINAL_HOUGH_INPUT_MODE_REGION_OF_INTEREST",
    "FINAL_HOUGH_INPUT_MODE_REGION_OF_INTEREST_AND_SCORE_FLOOR",
    "FINAL_HOUGH_INPUT_MODE_REGION_OF_INTEREST_OR_SCORE_FLOOR",
    "HoughPreprocessingConfig",
    "MEDIAN_ABSOLUTE_DEVIATION_BACKEND_MANUAL_NUMPY",
    "MEDIAN_ABSOLUTE_DEVIATION_BACKEND_SCIPY",
    "SCORE_FLOOR_METHOD_MEAN_PLUS_STANDARD_DEVIATION",
    "SCORE_FLOOR_METHOD_MEDIAN_PLUS_SCALED_MEDIAN_ABSOLUTE_DEVIATION",
    "SUPPORTED_ADAPTIVE_BUDGET_MASKS",
    "SUPPORTED_FINAL_HOUGH_INPUT_MODES",
    "SUPPORTED_SCORE_FLOOR_METHODS",
    "build_region_of_interest_hough_context",
]
