import argparse
import json
import math
import pickle
import re
import sys
from pathlib import Path

import numpy as np

"""\
Align prediction text blocks for ALL cases in scores.pkl using precomputed line
endpoints extracted from their chrF score matrices.

This script is a pipeline-friendly variant of `align_graph_text_blocks.py`:
- No hard-coded TARGET_GRAPHS list: processes every item in the scores.pkl stream.
- No hard-coded absolute paths: all file-system paths are provided via CLI args.
- Uses a precomputed endpoints pickle-stream (generated by
  `hough_line_transform_endpoints_no_angle_all.py`) so the probabilistic Hough-line
  transform is executed once and its endpoints are reused here.
- Output filenames are prefixed with a stable 4-digit index so they can be
  cross-referenced with visualisation outputs produced in the same item order.

High-level logic (per case):
1) Load item from scores.pkl (stream of pickled dicts).
2) Load merged Hough-line segments (endpoints) for this item from endpoints.pkl.
3) Convert endpoints into line dictionaries and filter lines for robustness.
4) Reorder prediction blocks using a single strategy:
   top-to-bottom line order, left-to-right within each line.
5) Assemble the adjusted prediction with overlap-aware stitching (stride).
6) Report normalized Levenshtein before/after and save outputs.
"""


# Ensure local project packages (evaluation/, etc.) are importable even when run
# from a different working directory.
PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from evaluation.evaluate_page import levenshtein_distance


def parse_args():
    p = argparse.ArgumentParser(
        description="Align prediction text blocks for all cases in scores.pkl using precomputed endpoints.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument(
        "--scores-pkl",
        type=Path,
        required=True,
        help="Path to compare.py output: a stream of pickled dict items.",
    )
    p.add_argument(
        "--endpoints-pkl",
        type=Path,
        required=True,
        help=(
            "Path to a pickle stream of per-item merged line endpoints (output of "
            "hough_line_transform_endpoints_no_angle_all.py)."
        ),
    )
    p.add_argument(
        "--output-dir",
        type=Path,
        required=True,
        help="Directory where adjusted text and JSON reports are written.",
    )
    p.add_argument(
        "--window-size",
        type=int,
        default=100,
        help="Window size used in compare.py (kept for metadata/reference).",
    )
    p.add_argument(
        "--window-stride",
        type=int,
        default=50,
        help="Window stride used in compare.py (used for block assembly here).",
    )
    p.add_argument(
        "--max-items",
        type=int,
        default=None,
        help="Limit the number of processed items (None means all).",
    )
    p.add_argument(
        "--visualise-full-dir",
        type=Path,
        default=None,
        help="Optional: path to visualiser full_figures/ for cross-references.",
    )
    p.add_argument(
        "--visualise-graph-dir",
        type=Path,
        default=None,
        help="Optional: path to visualiser graph_only/ for cross-references.",
    )
    p.add_argument(
        "--visualise-mask-dir",
        type=Path,
        default=None,
        help="Optional: path to visualiser detection_masks/ for cross-references.",
    )
    return p.parse_args()


def safe_name(name: str) -> str:
    """Normalize filename stem to a filesystem-safe token."""
    stem = Path(name).stem
    stem = re.sub(r"[^A-Za-z0-9._-]+", "_", stem)
    return stem[:120]


def safe_matrix(scores) -> np.ndarray:
    """Convert raw score payload to a clean 2D float matrix."""
    mat = np.asarray(scores, dtype=float)
    if mat.ndim != 2 or mat.size == 0:
        return np.zeros((1, 1), dtype=float)
    return np.nan_to_num(mat, nan=0.0, posinf=0.0, neginf=0.0)


def normalized_levenshtein_similarity(predicted_text: str, gold_text: str) -> float:
    """1 - levenshtein_distance(pred, gold) / max(len(pred), len(gold))."""
    denom = max(len(predicted_text), len(gold_text))
    if denom == 0:
        return 1.0
    return 1.0 - (levenshtein_distance(predicted_text, gold_text) / denom)


def line_y_at_x(line: dict, x: int) -> float:
    """Evaluate interpolated y-coordinate of a line at integer x."""
    x0, y0, x1, y1 = line["x0"], line["y0"], line["x1"], line["y1"]
    dx = x1 - x0
    if abs(dx) < 1e-8:
        return y0
    t = (x - x0) / dx
    return y0 + t * (y1 - y0)


def line_length(line: dict) -> float:
    """Euclidean length of a fitted line segment."""
    return float(math.hypot(line["x1"] - line["x0"], line["y1"] - line["y0"]))


def mean_line_support(matrix: np.ndarray, line: dict) -> float:
    """Mean matrix intensity sampled along a fitted line."""
    n_ref, n_pred = matrix.shape
    x_start = int(max(0, math.ceil(min(line["x0"], line["x1"])) ))
    x_end = int(min(n_pred - 1, math.floor(max(line["x0"], line["x1"])) ))
    if x_end < x_start:
        return 0.0

    vals = []
    for x in range(x_start, x_end + 1):
        y_idx = int(np.clip(round(line_y_at_x(line, x)), 0, n_ref - 1))
        vals.append(float(matrix[y_idx, x]))
    if not vals:
        return 0.0
    return float(np.mean(vals))


def lines_from_merged_segments(matrix: np.ndarray, merged_lines):
    """Convert merged segment endpoint pairs into line dictionaries in read order."""
    line_dicts = []
    for p0, p1 in merged_lines:
        x0, y0 = float(p0[0]), float(p0[1])
        x1, y1 = float(p1[0]), float(p1[1])
        if x1 < x0:
            x0, x1 = x1, x0
            y0, y1 = y1, y0
        score = mean_line_support(matrix, {"x0": x0, "y0": y0, "x1": x1, "y1": y1})
        line_dicts.append({"x0": x0, "y0": y0, "x1": x1, "y1": y1, "score": float(score)})

    return sorted(
        line_dicts,
        key=lambda ln: (min(ln["y0"], ln["y1"]), min(ln["x0"], ln["x1"])),
    )


def filter_lines_for_alignment(lines_read_order: list[dict], matrix: np.ndarray) -> list[dict]:
    """Keep only robust lines for block shifting."""
    if not lines_read_order:
        return []

    max_score = max(float(ln["score"]) for ln in lines_read_order)
    min_len = max(8.0, 0.08 * float(min(matrix.shape)))
    support_floor = float(np.percentile(matrix, 75))

    kept = []
    for ln in lines_read_order:
        ln2 = dict(ln)
        ln2["length"] = line_length(ln2)
        ln2["support"] = mean_line_support(matrix, ln2)

        if ln2["length"] < min_len:
            continue
        if ln2["score"] < 0.06 * max_score:
            continue
        if ln2["support"] < support_floor:
            continue
        kept.append(ln2)

    if not kept:
        best = max(lines_read_order, key=lambda ln: float(ln["score"]))
        best2 = dict(best)
        best2["length"] = line_length(best2)
        best2["support"] = mean_line_support(matrix, best2)
        return [best2]

    return sorted(kept, key=lambda ln: (min(ln["y0"], ln["y1"]), min(ln["x0"], ln["x1"])))


def build_pred_blocks(pred_text: str, n_pred: int, stride: int):
    """Build movable prediction blocks aligned to matrix x-axis indices."""
    starts = [j * stride for j in range(n_pred)]
    blocks = []
    for j, s in enumerate(starts):
        e = starts[j + 1] if (j + 1) < n_pred else len(pred_text)
        s = min(s, len(pred_text))
        e = min(max(e, s), len(pred_text))
        blocks.append(pred_text[s:e])
    return blocks


def assemble_from_order_with_stride(pred_text: str, order: list[int], n_pred: int, stride: int) -> str:
    """Assemble text from stride-based blocks, avoiding duplicate overlap."""
    blocks = build_pred_blocks(pred_text, n_pred=n_pred, stride=stride)
    if not order:
        return ""
    out = [blocks[order[0]]]
    for idx in order[1:]:
        block = blocks[idx]
        if stride <= 0 or len(block) <= stride:
            out.append(block)
        else:
            out.append(block[-stride:])
    return "".join(out)


def align_prediction_by_line_endpoints(
    pred_text: str,
    ref_text: str,
    matrix: np.ndarray,
    lines_read_order: list[dict],
    window_stride: int,
):
    """Reorder prediction blocks using dense-matrices style lines."""
    _n_ref, n_pred = matrix.shape

    lines_sorted = sorted(
        lines_read_order,
        key=lambda ln: (min(ln["y0"], ln["y1"]), min(ln["x0"], ln["x1"])),
    )

    block_to_line = {}
    for x in range(n_pred):
        candidates = []
        for lid, ln in enumerate(lines_sorted):
            x_min = int(math.floor(min(ln["x0"], ln["x1"])))
            x_max = int(math.ceil(max(ln["x0"], ln["x1"])))
            if x < x_min or x > x_max:
                continue
            y_est = line_y_at_x(ln, x)
            candidates.append((lid, abs(y_est)))
        if not candidates:
            continue
        candidates.sort(key=lambda t: t[1])
        block_to_line[x] = candidates[0][0]

    order = []
    used = set()
    for lid in range(len(lines_sorted)):
        xs = [x for x, ln_id in block_to_line.items() if ln_id == lid]
        xs.sort()
        for x in xs:
            if x not in used:
                used.add(x)
                order.append(x)

    for x in range(n_pred):
        if x not in used:
            order.append(x)

    adjusted_pred = assemble_from_order_with_stride(
        pred_text,
        order,
        n_pred=n_pred,
        stride=window_stride,
    )

    return {
        "adjusted_pred": adjusted_pred,
        "order": order,
        "strategy": "line_order_top_to_bottom",
        "candidate_scores": {},
        "mapped_y": None,
        "mapped_line_id": None,
        "target_rows": None,
        "n_pred_blocks": n_pred,
    }


def load_endpoints_by_fname(endpoints_pkl: Path) -> dict[str, dict]:
    """Load the endpoints pickle-stream into a fname->record mapping."""
    out: dict[str, dict] = {}
    with open(endpoints_pkl, "rb") as f:
        while True:
            try:
                rec = pickle.load(f)
            except EOFError:
                break
            fname = rec.get("fname")
            if not fname:
                continue
            out.setdefault(str(fname), rec)
    return out


def main():
    args = parse_args()

    output_dir = args.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    if not args.scores_pkl.exists():
        raise FileNotFoundError(f"Missing scores file: {args.scores_pkl}")
    if not args.endpoints_pkl.exists():
        raise FileNotFoundError(f"Missing endpoints file: {args.endpoints_pkl}")

    endpoints_by_fname = load_endpoints_by_fname(args.endpoints_pkl)
    if not endpoints_by_fname:
        raise RuntimeError(f"No endpoint records found in: {args.endpoints_pkl}")

    summary = []

    with open(args.scores_pkl, "rb") as f:
        idx = 0
        while True:
            try:
                item = pickle.load(f)
            except EOFError:
                break

            if args.max_items is not None and idx >= args.max_items:
                break

            fname = str(item.get("fname", f"item_{idx:04d}"))
            base_name = safe_name(Path(fname).name)
            case_prefix = f"{idx:04d}_{base_name}"

            endpoints_rec = endpoints_by_fname.get(fname)
            if endpoints_rec is None:
                raise KeyError(f"No endpoints found for fname={fname!r} in {args.endpoints_pkl}")

            merged_lines = endpoints_rec.get("merged_lines", [])
            threshold_start = float(endpoints_rec.get("threshold_start", float("nan")))

            matrix = safe_matrix(item.get("scores"))
            pred = str(item.get("pred", ""))
            ref = str(item.get("ref", ""))

            lines_read_order = lines_from_merged_segments(matrix, merged_lines)
            lines_for_alignment = filter_lines_for_alignment(lines_read_order, matrix)

            aligned = align_prediction_by_line_endpoints(
                pred_text=pred,
                ref_text=ref,
                matrix=matrix,
                lines_read_order=lines_for_alignment,
                window_stride=int(args.window_stride),
            )

            adjusted_pred = aligned["adjusted_pred"]

            before_nls = normalized_levenshtein_similarity(pred, ref)
            after_nls = normalized_levenshtein_similarity(adjusted_pred, ref)

            out_txt = output_dir / f"{case_prefix}_adjusted_pred.txt"
            out_report = output_dir / f"{case_prefix}_alignment_report.json"

            out_txt.write_text(adjusted_pred, encoding="utf-8")

            line_report = []
            for lid, ln in enumerate(lines_for_alignment):
                line_report.append(
                    {
                        "line_id": lid,
                        "x0": round(float(ln["x0"]), 4),
                        "y0": round(float(ln["y0"]), 4),
                        "x1": round(float(ln["x1"]), 4),
                        "y1": round(float(ln["y1"]), 4),
                        "score": round(float(ln["score"]), 6),
                        "length": round(float(ln.get("length", line_length(ln))), 4),
                        "support": round(float(ln.get("support", mean_line_support(matrix, ln))), 6),
                    }
                )

            vis_full = None
            vis_graph = None
            vis_mask = None
            if args.visualise_full_dir is not None:
                vis_full = str(args.visualise_full_dir / f"{idx:04d}_{base_name}_full.png")
            if args.visualise_graph_dir is not None:
                vis_graph = str(args.visualise_graph_dir / f"{idx:04d}_{base_name}_graph.png")
            if args.visualise_mask_dir is not None:
                vis_mask = str(args.visualise_mask_dir / f"{idx:04d}_{base_name}_mask.png")

            report = {
                "index": idx,
                "file_name": Path(fname).name,
                "matrix_shape": list(matrix.shape),
                "window_size": int(args.window_size),
                "window_stride": int(args.window_stride),
                "threshold_start": threshold_start,
                "endpoints_source": str(args.endpoints_pkl),
                "line_count_raw": int(endpoints_rec.get("raw_line_count", 0)),
                "line_count_selected": int(endpoints_rec.get("selected_line_count", 0)),
                "line_count_merged": int(endpoints_rec.get("merged_line_count", 0)),
                "line_count_used": len(lines_for_alignment),
                "lines_read_order": line_report,
                "selected_shift_strategy": aligned["strategy"],
                "candidate_scores": aligned["candidate_scores"],
                "total_pred_block_count": int(matrix.shape[1]),
                "before_normalized_levenshtein_similarity": before_nls,
                "after_normalized_levenshtein_similarity": after_nls,
                "delta": after_nls - before_nls,
                "adjusted_pred_path": str(out_txt),
                "visualise_full_path": vis_full,
                "visualise_graph_path": vis_graph,
                "visualise_mask_path": vis_mask,
                "endpoints_record_index": int(endpoints_rec.get("index", -1)),
            }

            out_report.write_text(
                json.dumps(report, indent=2, ensure_ascii=False),
                encoding="utf-8",
            )
            summary.append(report)

            print(
                f"{case_prefix}: before={before_nls:.6f}, after={after_nls:.6f}, "
                f"delta={after_nls - before_nls:.6f}, lines_used={len(lines_for_alignment)}, "
                f"strategy={aligned['strategy']}"
            )

            idx += 1

    summary_path = output_dir / "summary.json"
    summary_path.write_text(
        json.dumps(summary, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )

    print("Saved outputs to:", output_dir)


if __name__ == "__main__":
    main()
